version: '3.9'


services:
  postgresdb:
    image: "postgres:14.3"
    container_name: postgresdb
    env_file:
      - env/.env.dev
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  auth:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-dev
    container_name: auth
    env_file:
      - env/.env.dev
    volumes:
      - ./:/opt/auth
    depends_on:
      - postgresdb
    entrypoint: ""
    command: /home/bank-api/docker-entrypoint-dev.sh
    ports:
      - "8000:8000"


volumes:
  db_data: